// <auto-generated />
namespace application_development.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixtrainee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixtrainee));
        
        string IMigrationMetadata.Id
        {
            get { return "202106200715399_fix-trainee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
